//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pjt_support_tool")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub project_no: Option<i32>,
    pub pjt_support_tool_type1: Option<String>,
    pub pjt_support_tool_name1: Option<String>,
    pub pjt_support_tool_type2: Option<String>,
    pub pjt_support_tool_name2: Option<String>,
    pub pjt_support_tool_type3: Option<String>,
    pub pjt_support_tool_name3: Option<String>,
    pub pjt_support_tool_type4: Option<String>,
    pub pjt_support_tool_name4: Option<String>,
    pub pjt_support_tool_type5: Option<String>,
    pub pjt_support_tool_name5: Option<String>,
    pub pjt_support_tool_type6: Option<String>,
    pub pjt_support_tool_name6: Option<String>,
    pub pjt_support_tool_type7: Option<String>,
    pub pjt_support_tool_name7: Option<String>,
    pub pjt_support_tool_type8: Option<String>,
    pub pjt_support_tool_name8: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::work_experience::Entity",
        from = "Column::ProjectNo",
        to = "super::work_experience::Column::ProjectNo",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WorkExperience,
}

impl Related<super::work_experience::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkExperience.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
