//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::auth::Entity as Auth;
pub use super::departments::Entity as Departments;
pub use super::dev_tool::Entity as DevTool;
pub use super::dev_tool_mst::Entity as DevToolMst;
pub use super::employees::Entity as Employees;
pub use super::pjt_support_tool::Entity as PjtSupportTool;
pub use super::pjt_support_tool_mst::Entity as PjtSupportToolMst;
pub use super::qualification::Entity as Qualification;
pub use super::self_introduction::Entity as SelfIntroduction;
pub use super::work_experience::Entity as WorkExperience;

pub use super::todos::Entity as Todos;
pub use super::users::Entity as Users;